homeserver:
  address: http://localhost:8008
  domain: localhost
  asmux: false
  status_endpoint: ""
  message_send_checkpoint_endpoint: ""
  async_media: false
appservice:
  address: http://localhost:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: postgres
    uri: postgres://postgres:1234@localhost/bridge?sslmode=disable
    max_open_conns: 20
    max_idle_conns: 2
    conn_max_idle_time: ""
    conn_max_lifetime: ""
  provisioning:
    prefix: /_matrix/provision
    shared_secret: disable
    segment_key: ""
  id: foodtoshare
  bot:
    username: foodtosharebot
    displayname: FoodToShare bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
  ephemeral_events: false
  as_token: IMeedmA6SYuy4WYsa36sWCmjGrQuT3WxZ1ndBLHQUpWHcPkKxg3RUx7wXI09L9Hh
  hs_token: VD0rsKMBaPsPIcokdFxDIukhDKlsNLJrmWNM9i0ne2s1IEMtxKXdTb9Qo5E31ljs
bridge:
  username_template: fts_{{.UserID}}
  displayname_template: "{{.JID}}"
  community_template: fts_{{.Localpart}}={{.Server}}
  command_prefix: '!wa'
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug
  print_json: false
  file_json: false
