FROM alpine:3.19

ENV UID=1337 \
    GID=1337

RUN apk add --no-cache ffmpeg su-exec ca-certificates bash jq curl yq

ARG EXECUTABLE=./bridge
COPY $EXECUTABLE /usr/bin/bridge
COPY ./example-config.yaml /opt/bridge/example-config.yaml
COPY ./docker-run.sh /docker-run.sh
VOLUME /data

CMD ["/docker-run.sh"]