# Homeserver details.
homeserver:
  # The address that this appservice can use to connect to the homeserver.
  address: https://matrix.org
  # The domain of the homeserver (for MXIDs, etc).
  domain: matrix.org

# Application service host/registration related details.
# Changing these values requires regeneration of the registration.
appservice:
  # The address that the homeserver can use to connect to this appservice.
  address: http://localhost:8080

  # The hostname and port where this appservice should listen.
  hostname: 0.0.0.0
  port: 8080

  # Database config.
  database:
    # The database type. Only "sqlite3" is supported.
    type: sqlite3
    # The database URI. Usually file name. https://github.com/mattn/go-sqlite3#connection-string
    uri: foodtoshare.db

  # The unique ID of this appservice.
  id: foodtoshare
  # Appservice bot details.
  bot:
    # Username of the appservice bot.
    username: foodtosharebot
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    displayname: foodtoshare bridge bot
    avatar: 

  # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
  as_token: "This value is generated when generating the registration"
  hs_token: "This value is generated when generating the registration"

# Bridge config. Currently unused.
bridge:
  # Localpart template of MXIDs for Whatsapp users.
  # {{.receiver}} is replaced with the Whatsapp user ID of the Matrix user receiving messages.
  # {{.userid}} is replaced with the user ID of the Whatsapp user.
  username_template: "foodtoshare_{{.Receiver}}_{{.UserID}}"
  # Displayname template for Whatsapp users.
  # {{.displayname}} is replaced with the display name of the Whatsapp user.
  displayname_template: "{{.Displayname}}"

# Logging config.
logging:
  # The directory for log files. Will be created if not found.
  directory: ./logs
  # Available variables: .date for the file date and .index for different log files on the same day.
  file_name_format: {{.date}}-{{.index}.log
  # Date format for file names in the Go time format: https://golang.org/pkg/time/#pkg-constants
  file_date_format: 2006-01-02
  # Log file permissions.
  file_mode: 0600
  # Timestamp format for log entries in the Go time format.
  timestamp_format: Jan _2, 2006 15:04:05
  # Minimum severity for log messages.
  # Options: debug, info, warn, error, fatal
  print_level: info